### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by lidel** [xicombd/is-ipfs#1]
Fix:
```diff
-isIPFS.ipnsUrl('https://ipfs.io/ipfs/github.com') // true
+isIPFS.ipnsUrl('https://ipfs.io/ipns/github.com') // true
```

:)

**Comment by xicombd** [comment]
Thanks @lidel!

**Comment by lidel** [comment]
Aaaand 
```diff
-isIPFS.url('https://ipfs.io/ipfs/github.com') // true
+isIPFS.url('https://ipfs.io/ipfs/github.com') // false
```

:trollface:

**Comment by xicombd** [comment]
Ahaha, that one was on purpose as it demonstrates that it doesn't match invalid multihashes, even if `/ipfs/` is on the path, like `https://github.com/ipfs/js-ipfs` for example.

I will try make it more clear tough :)

**Comment by lidel** [comment]
Please double check the change from my last comment, I am quite sure that 
`isIPFS.url('https://ipfs.io/ipfs/github.com')` returns `false` :)

**Comment by xicombd** [comment]
It does, I [edited the comment](https://github.com/xicombd/is-ipfs/issues/1#issuecomment-182073125) and [fixed the typo](https://github.com/xicombd/is-ipfs/commit/77870992648ef9fa4b5780a6b2d092ac3f45fc7b#diff-04c6e90faac2675aa89e2176d2eec7d8L23) a few minutes ago :)
