### ISSUE TITLE
Path-only validation

### ISSUE THREAD

**Issue by lidel** [xicombd/is-ipfs#2]
During refactoring in [ipfs-firefox-addon](https://github.com/lidel/ipfs-firefox-addon) I noticed that we could use path-only validation.

If implemented, it should be analogous to the `url` one:

- `isIPFS.ipfsPath`
- `isIPFS.ipnsPath`
- `isIPFS.path`(for both)

```javascript
isIPFS.path('/ipfs/QmYHNYAaYK5hm3ZhZFx5W9H6xydKDGimjdgJMrMSdnctEm') // true
```

:gift:  :grey_question:

**Comment by xicombd** [comment]
Sounds like a great idea! :+1: 

I can have a look at that tomorrow, or feel free to PR it yourself :)

**Comment by lidel** [comment]
I'll PR :)

**Comment by lidel** [comment]
Ooops, I forgot to update `README`. 
I think you may want to add `ipfsPath`, `ipnsPath`, `path` and `urlOrPath` there – right now it is not advertised.

**Comment by xicombd** [comment]
Just added them here: https://github.com/xicombd/is-ipfs/commit/faad3a98742a05fed5ff0857fd198f346853177c

Please review in case some typo slipped by :)

**Comment by lidel** [comment]
https://github.com/xicombd/is-ipfs/commit/faad3a98742a05fed5ff0857fd198f346853177c is perfect :ok_hand:  but I've found my own typo in `test-path.js` :trolleybus: 
```diff
-test('isIPFS.path should not match an path without prefix', function (t) {
+test('isIPFS.path should not match a path without prefix', function (t) {
```
