### ISSUE TITLE
ES6 code

### ISSUE THREAD

**Issue by chpio** [xicombd/is-ipfs#4]
Hi, there is [es6 code](https://github.com/xicombd/is-ipfs/blob/73ccab3fae1d4bf200c81c54b556d7a5a028c026/index.js#L44-L55) in the repo. could lead to issues if executed on an old js runtime wo *arrow-function* support...

**Comment by xicombd** [comment]
That's true, I've been using it either with node 4+ or with `webpack` and `babel`.

However if you want to PR a dist build script, I would happily accept it :octocat:

**Comment by nginnever** [comment]
https://github.com/xicombd/is-ipfs/pull/5

Uses dignified.js and comes with a build script

**Comment by xicombd** [comment]
Going to close this now that #5 has been merged and published :rocket: 
Thank you all!
