### ISSUE TITLE
Update to aegir

### ISSUE THREAD

**Issue by diasdavid** [xicombd/is-ipfs#7]

**Comment by lidel** [comment]
Quick elaboration:

- Aegir is an opinionated tool for automated JavaScript project management
  - https://www.npmjs.com/package/aegir / https://github.com/dignifiedquire/aegir
  - already used by other JS libs for IPFS,  such as  [js-ipfs-api](https://github.com/ipfs/js-ipfs-api)
  - created browserified version that can be used in Browser (see #8)
