### ISSUE TITLE
Enable use in the Browser through browserify

### ISSUE THREAD

**Issue by lidel** [xicombd/is-ipfs#8]
Having browserified version would enable non-Node.js projects (eg. [ipfs-firefox-addon](https://github.com/lidel/ipfs-firefox-addon)) to use upstream version directly. 
It should  be possible to load official browserified artifact from IPFS mirror of NPM (with SRI validation).

It can be done manually or via move to AEgir (#7).

References: 
- [https://github.com/ipfs/js-ipfs-api](https://github.com/ipfs/js-ipfs-api) provides verified version: 
  - https://npmcdn.com/ipfs-api@9.0.0/dist/index.js
  - https://ipfs.io/ipfs/QmP3fUQAVpvbP3pM47byDa3QRsUbvMztk1F48UU85kgGSW

**Comment by xicombd** [comment]
Just finished #9, dist version is now available at https://unpkg.com/is-ipfs@0.2.1/dist/

@lidel Do we need to do anything for it to get on the  IPFS mirror of NPM or is it automatic?

**Comment by lidel** [comment]
Thanks! 

It should be automatic as long at least one person has  [npm-on-ipfs](https://github.com/diasdavid/npm-on-ipfs)  set up and running with `--clone`.
But just to be sure, I manually pinned everything in https://unpkg.com/is-ipfs@0.2.1/dist/.

For example:
https://unpkg.com/is-ipfs@0.2.1/dist/index.js → https://ipfs.io/ipfs/QmUqRvxzQyYWNY6cD1Hf168fXeqDTQWwZpyXjU5RUExciZ

**Comment by xicombd** [comment]
Awesome, thanks!
